package com.yahyafati.mnemo.core.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Light roles are copied verbatim from the Tailwind config in docs/design/*.html.
internal val MnemoLightColorScheme = lightColorScheme(
    primary = Color(0xFF3525CD),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFF4F46E5),
    onPrimaryContainer = Color(0xFFDAD7FF),
    inversePrimary = Color(0xFFC3C0FF),
    secondary = Color(0xFF006C49),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFF6CF8BB),
    onSecondaryContainer = Color(0xFF00714D),
    tertiary = Color(0xFF684000),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF885500),
    onTertiaryContainer = Color(0xFFFFD4A4),
    background = Color(0xFFFFF8F3),
    onBackground = Color(0xFF1D1B18),
    surface = Color(0xFFFFF8F3),
    onSurface = Color(0xFF1D1B18),
    surfaceVariant = Color(0xFFE7E1DC),
    onSurfaceVariant = Color(0xFF464555),
    surfaceTint = Color(0xFF4D44E3),
    inverseSurface = Color(0xFF32302D),
    inverseOnSurface = Color(0xFFF6F0EA),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF777587),
    outlineVariant = Color(0xFFC7C4D8),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFF8F3),
    surfaceContainer = Color(0xFFF3EDE7),
    surfaceContainerHigh = Color(0xFFEDE7E2),
    surfaceContainerHighest = Color(0xFFE7E1DC),
    surfaceContainerLow = Color(0xFFF9F2ED),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFDFD9D4),
)

// The mockups have no dark theme. These roles are generated with material-color-utilities
// (the Material Theme Builder engine) using the Fidelity variant seeded with #4F46E5, plus the
// mockups' own secondary (#6CF8BB), tertiary (#885500) and warm neutral (hue of #FFF8F3, chroma 4).
// With those inputs the generated *light* scheme reproduces the mockup's primary, secondary,
// tertiary, error and outline roles exactly, so this dark scheme is its matching counterpart.
internal val MnemoDarkColorScheme = darkColorScheme(
    primary = Color(0xFFC3C0FF),
    onPrimary = Color(0xFF1D00A5),
    primaryContainer = Color(0xFF4F46E5),
    onPrimaryContainer = Color(0xFFDAD7FF),
    inversePrimary = Color(0xFF4D44E3),
    secondary = Color(0xFF4FDEA3),
    onSecondary = Color(0xFF003824),
    secondaryContainer = Color(0xFF00B47D),
    onSecondaryContainer = Color(0xFF003E28),
    tertiary = Color(0xFFFDB963),
    onTertiary = Color(0xFF472A00),
    tertiaryContainer = Color(0xFF885500),
    onTertiaryContainer = Color(0xFFFFD4A4),
    background = Color(0xFF16130E),
    onBackground = Color(0xFFEAE1D9),
    surface = Color(0xFF16130E),
    onSurface = Color(0xFFEAE1D9),
    surfaceVariant = Color(0xFF464555),
    onSurfaceVariant = Color(0xFFC7C4D8),
    surfaceTint = Color(0xFFC3C0FF),
    inverseSurface = Color(0xFFEAE1D9),
    inverseOnSurface = Color(0xFF34302A),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF918FA1),
    outlineVariant = Color(0xFF464555),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF3D3833),
    surfaceContainer = Color(0xFF231F1A),
    surfaceContainerHigh = Color(0xFF2D2924),
    surfaceContainerHighest = Color(0xFF39342E),
    surfaceContainerLow = Color(0xFF1F1B16),
    surfaceContainerLowest = Color(0xFF110E09),
    surfaceDim = Color(0xFF16130E),
)
